Repository PHOTOX/ABIN, pull requests merged in 2022-04, with the labels that each got.

#102 GHA: support Plumed 2.8
  .github/workflows/gfortran.yml
  src/plumed.F90
  tests/PLUMED/test.sh
  unit_tests/Makefile
  unit_tests/test_plumed.pf
Labels: testing

#108 Mdstep refactor
  src/abin.F90
  src/analysis.F90
  src/ekin.F90
  src/en_restraint.F90
  src/force_terash.F90
  src/forces.F90
  src/fortran_interfaces.F90
  src/gle.F90
  src/init.F90
  src/mdstep.F90
  src/modules.F90
  src/plumed.F90
  src/transform.F90
  src/utils.F90
  unit_tests/test_masses.pf
Labels: refactor

#109 Refactor force_abin
  src/Makefile
  src/analysis.F90
  src/files.F90
  src/force_abin.F90
  src/force_tera.F90
  src/forces.F90
  src/fortran_interfaces.F90
  src/gle.F90
  src/init.F90
  src/io.F90
  src/landau_zener.F90
  src/plumed.F90
  src/qmmm.F90
  src/random.F90
  src/utils.F90
  tests/QMMM/MM/r.mm
  tests/WATER_FAIL/ABIN_ERROR1.ref
  tests/WATER_FAIL/ABIN_ERROR2.ref
  tests/WATER_FAIL/test.sh
  unit_tests/.gitignore
  unit_tests/Makefile
  unit_tests/test_interface.pf
Labels: refactor

#98 Add test for Lennard-Jones / Coulomb potential + refactor
  src/force_mm.F90
  src/forces.F90
  src/init.F90
  src/modules.F90
  src/vinit.F90
  tests/ABINITIO/DYN/dftb_in.hsd
  tests/ABINITIO/DYN/r.dyn
  tests/MM/energies.dat.ref
  tests/MM/forces.xyz.ref
  tests/MM/input.in
  tests/MM/input.in2
  tests/MM/mini.xyz
  tests/MM/movie.xyz.ref
  tests/MM/restart.xyz.1.ref
  tests/MM/restart.xyz.ref
  tests/MM/temper.dat.ref
  tests/MM/velocities.xyz.ref
  tests/QMMM/DYN/dftb_in.hsd
  tests/QMMM/DYN/r.dyn
  tests/QMMM/MM/dftb_in.hsd
  tests/test.sh
  unit_tests/.gitignore
  unit_tests/Makefile
  unit_tests/test_mm.pf
Labels: testing

#115 Migrate Codecov from bash uploader
  .github/codecov_bash_uploader.sh
  .github/workflows/gfortran.yml
  codecov.yml
  src/utils.F90
  unit_tests/test_mm.pf
Labels: testing

#110 Robust and reproducible PRNG initialization for REMD
  sample_inputs/input.in
  sample_inputs/input.in.cmd
  sample_inputs/input.in.gle
  sample_inputs/input.in.pigle
  sample_inputs/input.in.pimd
  sample_inputs/input.in.sh
  sample_inputs/input.in.shake
  src/analysis.F90
  src/cmdline.F90
  src/compile_info.F90
  src/init.F90
  src/modules.F90
  src/random.F90
  tests/CMDLINE/ERROR.ref
  tests/REMD/energies.dat.00.ref
  tests/REMD/energies.dat.01.ref
  tests/REMD/energies.dat.02.ref
  tests/REMD/movie.xyz.00.ref
  tests/REMD/movie.xyz.01.ref
  tests/REMD/movie.xyz.02.ref
  tests/REMD/remd.out.ref
  tests/REMD/restart.xyz.00.5.ref
  tests/REMD/restart.xyz.00.old.ref
  tests/REMD/restart.xyz.00.ref
  tests/REMD/restart.xyz.01.5.ref
  tests/REMD/restart.xyz.01.old.ref
  tests/REMD/restart.xyz.01.ref
  tests/REMD/restart.xyz.02.5.ref
  tests/REMD/restart.xyz.02.old.ref
  tests/REMD/restart.xyz.02.ref
  tests/REMD/temper.dat.00.ref
  tests/REMD/temper.dat.01.ref
  tests/REMD/temper.dat.02.ref
  tests/TERAPI-REMD/energies.dat.00.ref
  tests/TERAPI-REMD/energies.dat.01.ref
  tests/TERAPI-REMD/energies.dat.02.ref
  tests/TERAPI-REMD/input.in
  tests/TERAPI-REMD/movie.xyz.00.ref
  tests/TERAPI-REMD/movie.xyz.01.ref
  tests/TERAPI-REMD/movie.xyz.02.ref
  tests/TERAPI-REMD/remd.out.ref
  tests/TERAPI-REMD/restart.xyz.00.old.ref
  tests/TERAPI-REMD/restart.xyz.00.ref
  tests/TERAPI-REMD/restart.xyz.01.old.ref
  tests/TERAPI-REMD/restart.xyz.01.ref
  tests/TERAPI-REMD/restart.xyz.02.old.ref
  tests/TERAPI-REMD/restart.xyz.02.ref
  tests/TERAPI-REMD/temper.dat.00.ref
  tests/TERAPI-REMD/temper.dat.01.ref
  tests/TERAPI-REMD/temper.dat.02.ref
  unit_tests/.gitignore
  unit_tests/Makefile
  unit_tests/test_prng.pf
  utils/abin-randomint.f90
  utils/create_trajectories.sh
  utils/trajs-randomint.f90
Labels: refactor

#120 ERMD test
  src/en_restraint.F90
  src/files.F90
  src/init.F90
  tests/ERMD/G09ER/engrad_es
  tests/ERMD/G09ER/engrad_gs
  tests/ERMD/G09ER/r.g09er
  tests/ERMD/en_restraint.dat.ref
  tests/ERMD/input.in
  tests/ERMD/input.in2
  tests/ERMD/mini.xyz
  tests/test.sh
Labels: testing

#124 FIX: Read velocities from file in r.terabin
  src/cmdline.F90
  tests/CMDLINE/ABIN_ERROR1.ref
  tests/CMDLINE/ABIN_ERROR2.ref
  tests/CMDLINE/ABIN_ERROR3.ref
  tests/CMDLINE/ABIN_ERROR4.ref
  tests/CMDLINE/ABIN_ERROR5.ref
  tests/CMDLINE/test.sh
  utils/r.terabin
Labels: bug

#119 convert all system() calls to execute_command_line()
  src/abin.F90
  src/analysis.F90
  src/analyze_ext_template.F90
  src/compile_info.F90
  src/en_restraint.F90
  src/files.F90
  src/force_abin.F90
  src/force_cp2k.F90
  src/force_tera.F90
  src/force_terash.F90
  src/forces.F90
  src/init.F90
  src/landau_zener.F90
  src/remd.F90
  src/surfacehop.F90
  src/tera_mpi_api.F90
  src/utils.F90
  tests/.gitignore
  tests/ABINITIO-FAIL/DYN/engrad.dat.all.ref
  tests/ABINITIO-FAIL/DYN/r.dyn
  tests/ABINITIO-FAIL/ERROR.ref
  tests/ABINITIO-FAIL/input.in
  tests/ABINITIO-FAIL/mini.xyz
  tests/REMD/remd.out.ref
  tests/TERAPI-FAILS/ABIN_ERROR1.ref
  tests/TERAPI-FAILS/test3.sh
  tests/TERAPI-PIMD-PARALLEL/test.sh
  tests/TERAPI-PIMD/test.sh
  tests/TERAPI-REMD/remd.out.ref
  tests/TERAPI-REMD/test.sh
  tests/test.sh
  unit_tests/test_gle.pf
  unit_tests/test_interface.pf
Labels: refactor

#104 Use the correct decoherence correction by default
  src/sh_integ.F90
  tests/SH_BUTCHER/input.in
  tests/SH_BUTCHER/input.in2
  tests/SH_BUTCHER_PHASE/input.in
  tests/SH_BUTCHER_PHASE/input.in2
  tests/SH_RK4/input.in
  tests/SH_RK4/input.in2
  tests/SH_RK4_PHASE/input.in
  tests/SH_RK4_PHASE/input.in2
Labels: bug
